In [125]:
import numpy as np
from itertools import permutations

In [126]:
suche_max_fuer = ['Tomate', 'Spargel', 'Mangold']

alle moeglichkeiten

In [127]:
for i in list(permutations(suche_max_fuer)):
    print(i)

('Tomate', 'Spargel', 'Mangold')
('Tomate', 'Mangold', 'Spargel')
('Spargel', 'Tomate', 'Mangold')
('Spargel', 'Mangold', 'Tomate')
('Mangold', 'Tomate', 'Spargel')
('Mangold', 'Spargel', 'Tomate')


In [128]:
fname = r'Pflanzenfolge_Tabelle.csv'

In [129]:
gelistete_pflanzen = np.genfromtxt(fname,
                                   delimiter=",",
                                   dtype=None,
                                   encoding=None)[0,1:]
print(gelistete_pflanzen)

['Karotte' 'Spargel' 'Erbse' 'Radieschen' 'Tomate' 'Mangold']


In [130]:
pflanzen_uebergangs_matrix = np.genfromtxt(fname,
                                           delimiter=",")[2:,1:]
print(pflanzen_uebergangs_matrix)


[[ 1. nan nan nan nan nan]
 [ 0.  1. nan nan nan nan]
 [-1.  1.  0. nan nan nan]
 [ 1. -1.  1.  1. nan nan]
 [ 1.  0.  1. -1.  0. nan]]


was sind die indices der Pflanzen die ich suche in uebergangs_matri

In [131]:
sorter = np.argsort(gelistete_pflanzen)
sorter[np.searchsorted(gelistete_pflanzen, suche_max_fuer, sorter=sorter)]

array([4, 1, 5])

In [132]:
for i in list(permutations(suche_max_fuer)):
    print(i)
    sorter = np.argsort(gelistete_pflanzen)
    indices = sorter[np.searchsorted(gelistete_pflanzen, i, sorter=sorter)]
    print(indices)

('Tomate', 'Spargel', 'Mangold')
[4 1 5]
('Tomate', 'Mangold', 'Spargel')
[4 5 1]
('Spargel', 'Tomate', 'Mangold')
[1 4 5]
('Spargel', 'Mangold', 'Tomate')
[1 5 4]
('Mangold', 'Tomate', 'Spargel')
[5 4 1]
('Mangold', 'Spargel', 'Tomate')
[5 1 4]


In [133]:
indices

array([5, 1, 4])

In [134]:
pflanzen_uebergangs_matrix[5-1,4]

0.0

In [135]:
n = len(i)
for ix in range(0,n-1):
    print(indices[ix]-1, indices[ix+1])
    print(pflanzen_uebergangs_matrix[indices[ix]-1,indices[ix+1]])
    print("---")

4 1
0.0
---
0 4
nan
---


In [136]:
i

('Mangold', 'Spargel', 'Tomate')

In [137]:
indices[ix]

1

In [138]:
indices[ix+1]

4

In [161]:
n = len(i)
for ix in range(0,n-1):
    print(indices[ix]-1, indices[ix+1])
    print(pflanzen_uebergangs_matrix[indices[ix]-1,indices[ix+1]])
    print(np.isfinite(pflanzen_uebergangs_matrix[indices[ix]-1, indices[ix+1]]))
    if np.isfinite(pflanzen_uebergangs_matrix[indices[ix]-1, indices[ix+1]]):
        cur_val = pflanzen_uebergangs_matrix[indices[ix]-1, indices[ix+1]]        
    else:
        cur_val = pflanzen_uebergangs_matrix[indices[ix+1]-1, indices[ix]]
    print(cur_val)
    print("---")


4 1
0.0
True
0.0
---
0 4
nan
False
-1.0
---


In [151]:
cur_val

nan

In [148]:
pflanzen_uebergangs_matrix[indices[ix]-1, indices[ix+1]]

nan

In [94]:
pflanzen_uebergangs_matrix[indices[ix+1], indices[ix]-1]

1.0

In [101]:
# 'Mangold', 'Spargel'
# 5, 1
pflanzen_uebergangs_matrix[5-1,1]

0.0

In [103]:
# 'Spargel', 'Tomate'
# 1, 4
pflanzen_uebergangs_matrix[4-1, 1]

-1.0

In [172]:
def calc_performance_this_series(indices):
    n = len(i)
    this_series = 0
    for ix in range(0,n-1):
        # print(indices[ix]-1, indices[ix+1])
        # print(pflanzen_uebergangs_matrix[indices[ix]-1,indices[ix+1]])
        # print(np.isfinite(pflanzen_uebergangs_matrix[indices[ix]-1, indices[ix+1]]))
        if np.isfinite(pflanzen_uebergangs_matrix[indices[ix]-1, indices[ix+1]]):
            cur_val = pflanzen_uebergangs_matrix[indices[ix]-1, indices[ix+1]]        
        else:
            cur_val = pflanzen_uebergangs_matrix[indices[ix+1]-1, indices[ix]]
        this_series += cur_val
        #print(cur_val)
        #print("---")
    print(this_series)
    return this_series

In [174]:
for i in list(permutations(suche_max_fuer)):
    print(i)
    sorter = np.argsort(gelistete_pflanzen)
    indices = sorter[np.searchsorted(gelistete_pflanzen, i, sorter=sorter)]
    #print(indices)
    calc_performance_this_series(indices)

('Tomate', 'Spargel', 'Mangold')
-1.0
('Tomate', 'Mangold', 'Spargel')
0.0
('Spargel', 'Tomate', 'Mangold')
-1.0
('Spargel', 'Mangold', 'Tomate')
0.0
('Mangold', 'Tomate', 'Spargel')
-1.0
('Mangold', 'Spargel', 'Tomate')
-1.0
